[project]
name = "mlx-grpo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.2.0",
    "mlx>=0.22.0",
    "peft>=0.14.0",
    "torch>=2.6.0",
    "transformers>=4.48.2",
    "trl>=0.14.0",
]
