# Quick smoke test configuration with reduced parameters
# Use this for fast iteration and testing

# Use your converted model (change path if you moved it)
model_name = "utils/mlx_model"
output_dir = "outputs/smoke-test"
run_name   = "smoke-test-run"

# training (reduced for fast testing)
learning_rate = 1e-6
num_epochs = 1
batch_size = 1
gradient_accumulation_steps = 2
warmup_ratio = 0.1
max_grad_norm = 0.1
logging_steps = 1

# sampling / rollout (minimal for smoke test)
num_generations = 4         # minimal generations for testing
max_new_tokens = 64         # shorter completions
temperature = 0.7
clip_eps = 0.2
kl_coeff = 0.0

# eval & logging
eval_steps = 10
eval_samples = 50
eval_every_updates = 10
eval_subset_size = 50
eval_max_new_tokens = 64
log_jsonl = true

# system
seed = 42
use_compile = true

